CREATE SEQUENCE HUESPEDES_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE HABITACIONES_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE RESERVAS_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE ESTADO_R_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE ESTADO_H_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;


CREATE TABLE HUESPEDES(
    ID_HUESPED NUMBER DEFAULT HUESPEDES_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL UNIQUE,
    TELEFONO VARCHAR2(50) NOT NULL UNIQUE,
    DOCUMENTO VARCHAR2(50) NOT NULL,
    NACIONALIDAD VARCHAR2(50) NOT NULL
);


CREATE TABLE ESTADO_HABITACION(
    ID_ESTADO_H NUMBER DEFAULT ESTADO_H_SEQ.NEXTVAL PRIMARY KEY,
    DESCRIPCION VARCHAR2(50) NOT NULL
);

CREATE TABLE ESTADO_RESERVAS(
    ID_ESTADO_R NUMBER DEFAULT ESTADO_R_SEQ.NEXTVAL PRIMARY KEY,
    DESCRIPCION VARCHAR2(50) NOT NULL
);


CREATE TABLE HABITACIONES(
    ID_HABITACION NUMBER DEFAULT HABITACIONES_SEQ.NEXTVAL PRIMARY KEY,
    NUMERO NUMBER NOT NULL UNIQUE,
    TIPO VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(50) NOT NULL, 
    PRECIO NUMBER NOT NULL,
    CAPACIDAD NUMBER NOT NULL,
    ESTADO NUMBER NOT NULL, 
    CONSTRAINT FK_HABITACION_ESTADO FOREIGN KEY (ESTADO) REFERENCES ESTADO_HABITACION(ID_ESTADO_H)
);

CREATE TABLE RESERVAS(
    ID_RESERVA NUMBER DEFAULT RESERVAS_SEQ.NEXTVAL PRIMARY KEY,
    ID_HUESPED NUMBER NOT NULL, 
    ID_HABITACION NUMBER NOT NULL, 
    FECHA_ENTRADA DATE NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    NOCHES NUMBER NOT NULL,
    TOTAL NUMBER NOT NULL, 
    ESTADO NUMBER NOT NULL,
    CONSTRAINT FK_HUESPED_RESERVA FOREIGN KEY (ID_HUESPED) REFERENCES HUESPEDES(ID_HUESPED),
    CONSTRAINT FK_HABITACION_RESERVA FOREIGN KEY (ID_HABITACION) REFERENCES HABITACIONES(ID_HABITACION),
    CONSTRAINT FK_RESERVA_ESTADO FOREIGN KEY (ESTADO) REFERENCES ESTADO_RESERVAS(ID_ESTADO_R)
);
