create table HUESPEDES(

ID_HUESPED NUMBER NOT NULL PRIMARY KEY,
NOMBRE VARCHAR2(50) NOT NULL,
APELLIDO VARCHAR2(50) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL UNIQUE,
TELEFONO NUMBER(10) NOT NULL UNIQUE,
DOCUMENTO VARCHAR2(50) NOT NULL,
NACIONALIDAD VARCHAR2(50) NOT NULL,

CONSTRAINT HUESPED_PK PRIMARY KEY (ID_HUESPED)
);

CREATE TABLE HABITACIONES(

ID_HABITACION NUMBER PRIMARY KEY,
NUMERO NUMBER NOT NULL UNIQUE,
TIPO VARCHAR2(50)NOT NULL,
DESCRIPCION VARCHAR(50)NOT NULL,
PRECIO FLOAT NOT NULL,
CAPACIDAD NUMBER NOT NULL,
ESTADO NUMBER NOT NULL,

CONSTRAINT HABITACIONES_PK PRIMARY KEY (ID_HABITACION)

);


CREATE TABLE RESERVAS(

ID_RESERVA NUMBER NOT NULL,
HUESPED VARCHAR2(50) NOT NULL,
HABITACION NUMBER NOT NULL,
FECHA_ENTRADA DATE NOT NULL,
FECHA_SALIDA DATE NOT NULL,
NOCHES NUMBER NOT NULL,
TOTAL NUMBER NOT NULL,
ESTADO NUMBER NOT NULL,


CONSTRAINT RESERVAS_PK PRIMARY KEY (ID_RESERVA),
CONSTRAINT FK_HUESPED_RESERVA FOREIGN KEY (ID_HUESPED) REFERENCES HUESPED(ID_HUESPED),
CONSTRAINT FK_HUESPED_ESTADO FOREIGN KEY (ID_ESTADO_R) REFERENCES ESTADO_RESERVAS(ID_ESTADO_R)

);
-----------------------------------------------------------






